### ISSUE TITLE
Misc Bug Fixes

### ISSUE THREAD

**Issue by StefanGreve** [Advanced-Systems/anonpy#46]
### Discussed in https://github.com/Advanced-Systems/anonpy/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **StefanGreve** September 21, 2023</sup>
## Preamble

This ticket describes first and foremost a small collection of bugs that were discovered during usability tests. However, it's also labeled as enhancement because we want to take this as an opportunity to refactor some of the code here as well.

## Requirements

- [ ] The library should throw an exception eagerly if the user attempts to import this package with an insufficient version, so add these lines to `src/anonpy/__init__.py`:
```python
import sys

python_major, python_minor = (3,11)

try:
    assert sys.version_info >= (python_major, python_minor)
except AssertionError:
    raise RuntimeError(f"{__package__!r} requires Python {python_major}.{python_minor}+ (You have Python {sys.version})")
```
- [ ] The `AnonPy` class inherits from `LogHander` which isn't necessary, at all:
```diff
src/anonpy/anonpy.py@14
- class AnonPy(RequestHandler, LogHandler):
+ class AnonPy(RequestHandler):
```

- [ ] A test application revealed the following bug that slipped through the unit tests that (console logging), as a consequence of which a `TypeError` would have been raised: 

```diff
# src/anonpy/internals/log_handlers.py@84
+ self.handlers["console"] = console
```

## Remarks

- Due to inheritance, the `AnonPy` class currently takes a lot of parameters
- Maybe the `enable_logging` parameter could be moved over to the `LogHandler` class, to be turned into a builder function? This would also encourage to pass `LogHandler` as a parameter, which loosens up the relationship between `AnonPy` and `LogHandler`

## Planning Status

Scheduled for version 1.0.0</div>

**Comment by MyrtleTurtle22** [comment]
I added the bug fixes outlined above.

**Comment by StefanGreve** [comment]
Suggested bug fixes were insufficient to meet the contributing guidelines, assigning this issue to myself now.
